version: '2'
services:
  consul:
    image: shcoder/consul
    container_name: consul
    restart: always
    ports:
      - 53:53/udp
    entrypoint:
      - /bin/start
      - -bootstrap
      - -server
      - -client 0.0.0.0
      - -ui-dir /ui

  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    entrypoint:
      - /bin/registrator
      - -internal
      - consul://consul:8500
    links:
      - consul

  proxy:
    image: shcoder/nginx-proxy-consul-template
    container_name: nginx_proxy
    restart: always
    ports:
      - 80:80
    links:
      - consul
      - registrator
    environment:
      - CONSUL_URL=consul:8500
      - SERVICE_80_NAME=nginx_proxy

networks:
  default:
    external:
      name: app